# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.litecoin_transaction_output import LitecoinTransactionOutput

class TestLitecoinTransactionOutput(unittest.TestCase):
    """LitecoinTransactionOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LitecoinTransactionOutput:
        """Test LitecoinTransactionOutput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LitecoinTransactionOutput`
        """
        model = LitecoinTransactionOutput()
        if include_optional:
            return LitecoinTransactionOutput(
                signed_tx = '',
                transaction_hash = ''
            )
        else:
            return LitecoinTransactionOutput(
        )
        """

    def testLitecoinTransactionOutput(self):
        """Test LitecoinTransactionOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
