# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.erc1155_response import Erc1155Response

class TestErc1155Response(unittest.TestCase):
    """Erc1155Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Erc1155Response:
        """Test Erc1155Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Erc1155Response`
        """
        model = Erc1155Response()
        if include_optional:
            return Erc1155Response(
                type = 1.337,
                chain_id = 1.337,
                data = '',
                gas = '',
                gas_price = '',
                gas_tip_cap = '',
                gas_fee_cap = '',
                value = '',
                nonce = 1.337,
                var_from = '',
                to = '',
                blob_gas = '',
                blob_gas_fee_cap = '',
                blob_hashes = [
                    ''
                    ],
                v = '',
                r = '',
                s = '',
                balance_of = '',
                balance_of_batch = ''
            )
        else:
            return Erc1155Response(
        )
        """

    def testErc1155Response(self):
        """Test Erc1155Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
