# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.eos_api import EosApi


class TestEosApi(unittest.TestCase):
    """EosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EosApi()

    def tearDown(self) -> None:
        pass

    def test_create_eos_account(self) -> None:
        """Test case for create_eos_account

        """
        pass

    def test_get_eos_account(self) -> None:
        """Test case for get_eos_account

        """
        pass

    def test_list_eos_accounts(self) -> None:
        """Test case for list_eos_accounts

        """
        pass

    def test_sign_eos_transaction(self) -> None:
        """Test case for sign_eos_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
