# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.oneinch_api import OneinchApi


class TestOneinchApi(unittest.TestCase):
    """OneinchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OneinchApi()

    def tearDown(self) -> None:
        pass

    def test_approve_call_data(self) -> None:
        """Test case for approve_call_data

        """
        pass

    def test_approve_spender(self) -> None:
        """Test case for approve_spender

        """
        pass

    def test_protocols(self) -> None:
        """Test case for protocols

        """
        pass

    def test_quote(self) -> None:
        """Test case for quote

        """
        pass

    def test_swap(self) -> None:
        """Test case for swap

        """
        pass

    def test_tokens(self) -> None:
        """Test case for tokens

        """
        pass


if __name__ == '__main__':
    unittest.main()
