# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.uni_swap_api import UniSwapApi


class TestUniSwapApi(unittest.TestCase):
    """UniSwapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UniSwapApi()

    def tearDown(self) -> None:
        pass

    def test_add_liquidity(self) -> None:
        """Test case for add_liquidity

        """
        pass

    def test_remove_liquidity(self) -> None:
        """Test case for remove_liquidity

        """
        pass

    def test_swap_exact_eth_for_tokens(self) -> None:
        """Test case for swap_exact_eth_for_tokens

        """
        pass

    def test_swap_exact_tokens_for_tokens(self) -> None:
        """Test case for swap_exact_tokens_for_tokens

        """
        pass


if __name__ == '__main__':
    unittest.main()
