# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.tron_api import TronApi


class TestTronApi(unittest.TestCase):
    """TronApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TronApi()

    def tearDown(self) -> None:
        pass

    def test_create_tron_account(self) -> None:
        """Test case for create_tron_account

        """
        pass

    def test_get_tron_account(self) -> None:
        """Test case for get_tron_account

        """
        pass

    def test_list_tron_accounts(self) -> None:
        """Test case for list_tron_accounts

        """
        pass

    def test_sign_tron_transaction(self) -> None:
        """Test case for sign_tron_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
