# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.transaction_input_supported_params import TransactionInputSupportedParams

class TestTransactionInputSupportedParams(unittest.TestCase):
    """TransactionInputSupportedParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionInputSupportedParams:
        """Test TransactionInputSupportedParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionInputSupportedParams`
        """
        model = TransactionInputSupportedParams()
        if include_optional:
            return TransactionInputSupportedParams(
                partner_data = openapi_client.models.transaction_input_supported_params_partner_data.TransactionInput_supportedParams_partnerData(
                    redirect_url = openapi_client.models.transaction_input_supported_params_partner_data_redirect_url.TransactionInput_supportedParams_partnerData_redirectUrl(
                        success = '', ), ),
                theme = openapi_client.models.transaction_input_supported_params_theme.TransactionInput_supportedParams_theme(
                    border_radius = 1.337, 
                    card_color = '', 
                    secondary_text_color = '', 
                    primary_text_color = '', 
                    secondary_color = '', 
                    primary_color = '', 
                    theme_name = '', 
                    is_dark = True, )
            )
        else:
            return TransactionInputSupportedParams(
                partner_data = openapi_client.models.transaction_input_supported_params_partner_data.TransactionInput_supportedParams_partnerData(
                    redirect_url = openapi_client.models.transaction_input_supported_params_partner_data_redirect_url.TransactionInput_supportedParams_partnerData_redirectUrl(
                        success = '', ), ),
                theme = openapi_client.models.transaction_input_supported_params_theme.TransactionInput_supportedParams_theme(
                    border_radius = 1.337, 
                    card_color = '', 
                    secondary_text_color = '', 
                    primary_text_color = '', 
                    secondary_color = '', 
                    primary_color = '', 
                    theme_name = '', 
                    is_dark = True, ),
        )
        """

    def testTransactionInputSupportedParams(self):
        """Test TransactionInputSupportedParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
