# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cosmos_api import CosmosApi


class TestCosmosApi(unittest.TestCase):
    """CosmosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CosmosApi()

    def tearDown(self) -> None:
        pass

    def test_create_cosmos_account(self) -> None:
        """Test case for create_cosmos_account

        """
        pass

    def test_get_cosmos_account(self) -> None:
        """Test case for get_cosmos_account

        """
        pass

    def test_list_cosmos_accounts(self) -> None:
        """Test case for list_cosmos_accounts

        """
        pass

    def test_sign_cosmos_transaction(self) -> None:
        """Test case for sign_cosmos_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
