# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.i_old_nft_approval import IOldNFTApproval

class TestIOldNFTApproval(unittest.TestCase):
    """IOldNFTApproval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IOldNFTApproval:
        """Test IOldNFTApproval
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IOldNFTApproval`
        """
        model = IOldNFTApproval()
        if include_optional:
            return IOldNFTApproval(
                erc721 = [
                    openapi_client.models.inft_approval_erc721.INFTApprovalERC721(
                        transaction_hash = '', 
                        contract = '', 
                        log_index = '', 
                        owner = '', 
                        approved = '', 
                        token_id = '', 
                        token_contract_type = '', 
                        token_name = '', 
                        token_symbol = '', )
                    ],
                erc1155 = [
                    openapi_client.models.inft_approval_erc1155.INFTApprovalERC1155(
                        transaction_hash = '', 
                        contract = '', 
                        log_index = '', 
                        account = '', 
                        operator = '', 
                        approved = True, 
                        token_contract_type = '', 
                        token_name = '', 
                        token_symbol = '', )
                    ]
            )
        else:
            return IOldNFTApproval(
                erc721 = [
                    openapi_client.models.inft_approval_erc721.INFTApprovalERC721(
                        transaction_hash = '', 
                        contract = '', 
                        log_index = '', 
                        owner = '', 
                        approved = '', 
                        token_id = '', 
                        token_contract_type = '', 
                        token_name = '', 
                        token_symbol = '', )
                    ],
                erc1155 = [
                    openapi_client.models.inft_approval_erc1155.INFTApprovalERC1155(
                        transaction_hash = '', 
                        contract = '', 
                        log_index = '', 
                        account = '', 
                        operator = '', 
                        approved = True, 
                        token_contract_type = '', 
                        token_name = '', 
                        token_symbol = '', )
                    ],
        )
        """

    def testIOldNFTApproval(self):
        """Test IOldNFTApproval"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
