# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.erc20_response import Erc20Response

class TestErc20Response(unittest.TestCase):
    """Erc20Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Erc20Response:
        """Test Erc20Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Erc20Response`
        """
        model = Erc20Response()
        if include_optional:
            return Erc20Response(
                type = 1.337,
                chain_id = 1.337,
                data = '',
                gas = '',
                gas_price = '',
                gas_tip_cap = '',
                gas_fee_cap = '',
                value = '',
                nonce = 1.337,
                var_from = '',
                to = '',
                blob_gas = '',
                blob_gas_fee_cap = '',
                blob_hashes = [
                    ''
                    ],
                v = '',
                r = '',
                s = '',
                name = '',
                symbol = '',
                decimals = '',
                total_supply = '',
                contract_address = '',
                balance_of = '',
                allowance = ''
            )
        else:
            return Erc20Response(
        )
        """

    def testErc20Response(self):
        """Test Erc20Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
