# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_broadcast_tx(self) -> None:
        """Test case for broadcast_tx

        """
        pass

    def test_create_account(self) -> None:
        """Test case for create_account

        """
        pass

    def test_delete_account(self) -> None:
        """Test case for delete_account

        """
        pass

    def test_deploy_contract(self) -> None:
        """Test case for deploy_contract

        """
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        """
        pass

    def test_get_balance(self) -> None:
        """Test case for get_balance

        """
        pass

    def test_get_nonce(self) -> None:
        """Test case for get_nonce

        """
        pass

    def test_list_accounts(self) -> None:
        """Test case for list_accounts

        """
        pass

    def test_sign_message(self) -> None:
        """Test case for sign_message

        """
        pass

    def test_sign_transaction(self) -> None:
        """Test case for sign_transaction

        """
        pass

    def test_sign_typed_data(self) -> None:
        """Test case for sign_typed_data

        """
        pass

    def test_transfer_eth(self) -> None:
        """Test case for transfer_eth

        """
        pass


if __name__ == '__main__':
    unittest.main()
