# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.aave_api import AaveApi


class TestAaveApi(unittest.TestCase):
    """AaveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AaveApi()

    def tearDown(self) -> None:
        pass

    def test_borrow(self) -> None:
        """Test case for borrow

        """
        pass

    def test_lend(self) -> None:
        """Test case for lend

        """
        pass

    def test_repay(self) -> None:
        """Test case for repay

        """
        pass

    def test_user_reserve_data(self) -> None:
        """Test case for user_reserve_data

        """
        pass


if __name__ == '__main__':
    unittest.main()
