# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.onramper_api import OnramperApi


class TestOnramperApi(unittest.TestCase):
    """OnramperApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OnramperApi()

    def tearDown(self) -> None:
        pass

    def test_on_ramper_checkout(self) -> None:
        """Test case for on_ramper_checkout

        """
        pass

    def test_on_ramper_get_quotes_buy(self) -> None:
        """Test case for on_ramper_get_quotes_buy

        """
        pass

    def test_on_ramper_get_quotes_sell(self) -> None:
        """Test case for on_ramper_get_quotes_sell

        """
        pass

    def test_on_ramper_get_supported_assets(self) -> None:
        """Test case for on_ramper_get_supported_assets

        """
        pass

    def test_on_ramper_get_supported_currencies(self) -> None:
        """Test case for on_ramper_get_supported_currencies

        """
        pass

    def test_on_ramper_get_supported_defaults_all(self) -> None:
        """Test case for on_ramper_get_supported_defaults_all

        """
        pass

    def test_on_ramper_get_supported_on_ramps_all(self) -> None:
        """Test case for on_ramper_get_supported_on_ramps_all

        """
        pass

    def test_on_ramper_get_supported_payment_types(self) -> None:
        """Test case for on_ramper_get_supported_payment_types

        """
        pass

    def test_on_ramper_get_supported_payment_types_fiat(self) -> None:
        """Test case for on_ramper_get_supported_payment_types_fiat

        """
        pass


if __name__ == '__main__':
    unittest.main()
