# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.solana_input import SolanaInput

class TestSolanaInput(unittest.TestCase):
    """SolanaInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SolanaInput:
        """Test SolanaInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SolanaInput`
        """
        model = SolanaInput()
        if include_optional:
            return SolanaInput(
                network = '',
                private_key = ''
            )
        else:
            return SolanaInput(
        )
        """

    def testSolanaInput(self):
        """Test SolanaInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
