# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.eos_api_response import EosAPIResponse

class TestEosAPIResponse(unittest.TestCase):
    """EosAPIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EosAPIResponse:
        """Test EosAPIResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EosAPIResponse`
        """
        model = EosAPIResponse()
        if include_optional:
            return EosAPIResponse(
                success = True,
                message = '',
                data = moonsdk.models.eos_transaction_output.EosTransactionOutput(
                    signed_tx = '', 
                    transaction_hash = '', )
            )
        else:
            return EosAPIResponse(
                success = True,
                message = '',
        )
        """

    def testEosAPIResponse(self):
        """Test EosAPIResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
