# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.ripple_api import RippleApi


class TestRippleApi(unittest.TestCase):
    """RippleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RippleApi()

    def tearDown(self) -> None:
        pass

    def test_create_ripple_account(self) -> None:
        """Test case for create_ripple_account

        """
        pass

    def test_get_ripple_account(self) -> None:
        """Test case for get_ripple_account

        """
        pass

    def test_list_ripple_accounts(self) -> None:
        """Test case for list_ripple_accounts

        """
        pass

    def test_sign_ripple_transaction(self) -> None:
        """Test case for sign_ripple_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
