# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.ens_resolve_input import EnsResolveInput

class TestEnsResolveInput(unittest.TestCase):
    """EnsResolveInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnsResolveInput:
        """Test EnsResolveInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnsResolveInput`
        """
        model = EnsResolveInput()
        if include_optional:
            return EnsResolveInput(
                domain = '',
                chain_id = ''
            )
        else:
            return EnsResolveInput(
                domain = '',
                chain_id = '',
        )
        """

    def testEnsResolveInput(self):
        """Test EnsResolveInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
