# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.yearn_api import YearnApi


class TestYearnApi(unittest.TestCase):
    """YearnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = YearnApi()

    def tearDown(self) -> None:
        pass

    def test_add_liquidity(self) -> None:
        """Test case for add_liquidity

        """
        pass

    def test_add_liquidity_weth(self) -> None:
        """Test case for add_liquidity_weth

        """
        pass

    def test_remove_liquidity(self) -> None:
        """Test case for remove_liquidity

        """
        pass

    def test_remove_liquidity_weth(self) -> None:
        """Test case for remove_liquidity_weth

        """
        pass


if __name__ == '__main__':
    unittest.main()
