# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.conveyor_finance_api import ConveyorFinanceApi


class TestConveyorFinanceApi(unittest.TestCase):
    """ConveyorFinanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConveyorFinanceApi()

    def tearDown(self) -> None:
        pass

    def test_swap(self) -> None:
        """Test case for swap

        """
        pass


if __name__ == '__main__':
    unittest.main()
