# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.aave_input import AaveInput

class TestAaveInput(unittest.TestCase):
    """AaveInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AaveInput:
        """Test AaveInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AaveInput`
        """
        model = AaveInput()
        if include_optional:
            return AaveInput(
                to = '',
                data = '',
                input = '',
                value = '',
                nonce = '',
                gas = '',
                gas_price = '',
                chain_id = '',
                encoding = '',
                eoa = True,
                contract_address = '',
                token_id = '',
                token_ids = '',
                approved = True,
                broadcast = True,
                lending_pool = '',
                amount = '',
                atoken_to_redeeem = '',
                ref_code = '',
                interest_rate_mode = ''
            )
        else:
            return AaveInput(
        )
        """

    def testAaveInput(self):
        """Test AaveInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
