# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.fiat_currency import FiatCurrency

class TestFiatCurrency(unittest.TestCase):
    """FiatCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiatCurrency:
        """Test FiatCurrency
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiatCurrency`
        """
        model = FiatCurrency()
        if include_optional:
            return FiatCurrency(
                icon = '',
                symbol = '',
                name = '',
                code = '',
                id = ''
            )
        else:
            return FiatCurrency(
                icon = '',
                symbol = '',
                name = '',
                code = '',
                id = '',
        )
        """

    def testFiatCurrency(self):
        """Test FiatCurrency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
