# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.transaction_input_supported_params_partner_data import TransactionInputSupportedParamsPartnerData

class TestTransactionInputSupportedParamsPartnerData(unittest.TestCase):
    """TransactionInputSupportedParamsPartnerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionInputSupportedParamsPartnerData:
        """Test TransactionInputSupportedParamsPartnerData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionInputSupportedParamsPartnerData`
        """
        model = TransactionInputSupportedParamsPartnerData()
        if include_optional:
            return TransactionInputSupportedParamsPartnerData(
                redirect_url = openapi_client.models.transaction_input_supported_params_partner_data_redirect_url.TransactionInput_supportedParams_partnerData_redirectUrl(
                    success = '', )
            )
        else:
            return TransactionInputSupportedParamsPartnerData(
                redirect_url = openapi_client.models.transaction_input_supported_params_partner_data_redirect_url.TransactionInput_supportedParams_partnerData_redirectUrl(
                    success = '', ),
        )
        """

    def testTransactionInputSupportedParamsPartnerData(self):
        """Test TransactionInputSupportedParamsPartnerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
