# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.inft_transfer import INFTTransfer

class TestINFTTransfer(unittest.TestCase):
    """INFTTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> INFTTransfer:
        """Test INFTTransfer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `INFTTransfer`
        """
        model = INFTTransfer()
        if include_optional:
            return INFTTransfer(
                transaction_hash = '',
                contract = '',
                log_index = '',
                token_contract_type = '',
                token_name = '',
                token_symbol = '',
                triggers = [
                    openapi_client.models.trigger_output.TriggerOutput(
                        value = null, 
                        name = '', )
                    ],
                operator = '',
                var_from = '',
                to = '',
                token_id = '',
                amount = ''
            )
        else:
            return INFTTransfer(
                transaction_hash = '',
                contract = '',
                log_index = '',
                token_contract_type = '',
                token_name = '',
                token_symbol = '',
                operator = '',
                var_from = '',
                to = '',
                token_id = '',
                amount = '',
        )
        """

    def testINFTTransfer(self):
        """Test INFTTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
