# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.supported_asset_response import SupportedAssetResponse

class TestSupportedAssetResponse(unittest.TestCase):
    """SupportedAssetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupportedAssetResponse:
        """Test SupportedAssetResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupportedAssetResponse`
        """
        model = SupportedAssetResponse()
        if include_optional:
            return SupportedAssetResponse(
                country = '',
                assets = [
                    moonsdk.models.supported_asset_response_assets_inner.SupportedAssetResponse_assets_inner(
                        crypto = [
                            ''
                            ], 
                        payment_methods = [
                            ''
                            ], 
                        fiat = '', )
                    ]
            )
        else:
            return SupportedAssetResponse(
                country = '',
                assets = [
                    moonsdk.models.supported_asset_response_assets_inner.SupportedAssetResponse_assets_inner(
                        crypto = [
                            ''
                            ], 
                        payment_methods = [
                            ''
                            ], 
                        fiat = '', )
                    ],
        )
        """

    def testSupportedAssetResponse(self):
        """Test SupportedAssetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
