# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.sell_quote import SellQuote

class TestSellQuote(unittest.TestCase):
    """SellQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SellQuote:
        """Test SellQuote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SellQuote`
        """
        model = SellQuote()
        if include_optional:
            return SellQuote(
                recommendations = [
                    ''
                    ],
                quote_id = '',
                payment_method = '',
                ramp = '',
                payout = 1.337,
                transaction_fee = 1.337,
                network_fee = 1.337,
                rate = 1.337
            )
        else:
            return SellQuote(
                recommendations = [
                    ''
                    ],
                quote_id = '',
                payment_method = '',
                ramp = '',
                payout = 1.337,
                transaction_fee = 1.337,
                network_fee = 1.337,
                rate = 1.337,
        )
        """

    def testSellQuote(self):
        """Test SellQuote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
