# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.ripple_api_response import RippleAPIResponse

class TestRippleAPIResponse(unittest.TestCase):
    """RippleAPIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RippleAPIResponse:
        """Test RippleAPIResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RippleAPIResponse`
        """
        model = RippleAPIResponse()
        if include_optional:
            return RippleAPIResponse(
                success = True,
                message = '',
                data = moonsdk.models.ripple_transaction_output.RippleTransactionOutput(
                    signed_tx = '', 
                    transaction_hash = '', )
            )
        else:
            return RippleAPIResponse(
                success = True,
                message = '',
        )
        """

    def testRippleAPIResponse(self):
        """Test RippleAPIResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
