# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.erc721_api import Erc721Api


class TestErc721Api(unittest.TestCase):
    """Erc721Api unit test stubs"""

    def setUp(self) -> None:
        self.api = Erc721Api()

    def tearDown(self) -> None:
        pass

    def test_approve(self) -> None:
        """Test case for approve

        """
        pass

    def test_balance_of(self) -> None:
        """Test case for balance_of

        """
        pass

    def test_get_approved(self) -> None:
        """Test case for get_approved

        """
        pass

    def test_is_approved_for_all(self) -> None:
        """Test case for is_approved_for_all

        """
        pass

    def test_name(self) -> None:
        """Test case for name

        """
        pass

    def test_owner_of(self) -> None:
        """Test case for owner_of

        """
        pass

    def test_safe_transfer_from(self) -> None:
        """Test case for safe_transfer_from

        """
        pass

    def test_set_approval_for_all(self) -> None:
        """Test case for set_approval_for_all

        """
        pass

    def test_symbol(self) -> None:
        """Test case for symbol

        """
        pass

    def test_token_uri(self) -> None:
        """Test case for token_uri

        """
        pass

    def test_transfer(self) -> None:
        """Test case for transfer

        """
        pass

    def test_transfer_from(self) -> None:
        """Test case for transfer_from

        """
        pass


if __name__ == '__main__':
    unittest.main()
