# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.bitcoin_api import BitcoinApi


class TestBitcoinApi(unittest.TestCase):
    """BitcoinApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BitcoinApi()

    def tearDown(self) -> None:
        pass

    def test_create_bitcoin_account(self) -> None:
        """Test case for create_bitcoin_account

        """
        pass

    def test_get_bitcoin_account(self) -> None:
        """Test case for get_bitcoin_account

        """
        pass

    def test_list_bitcoin_accounts(self) -> None:
        """Test case for list_bitcoin_accounts

        """
        pass

    def test_sign_bitcoin_transaction(self) -> None:
        """Test case for sign_bitcoin_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
