# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.litecoin_input import LitecoinInput

class TestLitecoinInput(unittest.TestCase):
    """LitecoinInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LitecoinInput:
        """Test LitecoinInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LitecoinInput`
        """
        model = LitecoinInput()
        if include_optional:
            return LitecoinInput(
                network = '',
                private_key = ''
            )
        else:
            return LitecoinInput(
        )
        """

    def testLitecoinInput(self):
        """Test LitecoinInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
