# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.get_supported_on_ramps_response_message_inner import GetSupportedOnRampsResponseMessageInner

class TestGetSupportedOnRampsResponseMessageInner(unittest.TestCase):
    """GetSupportedOnRampsResponseMessageInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSupportedOnRampsResponseMessageInner:
        """Test GetSupportedOnRampsResponseMessageInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSupportedOnRampsResponseMessageInner`
        """
        model = GetSupportedOnRampsResponseMessageInner()
        if include_optional:
            return GetSupportedOnRampsResponseMessageInner(
                id = '',
                display_name = '',
                icons = moonsdk.models.get_supported_on_ramps_response_message_inner_icons.GetSupportedOnRampsResponse_message_inner_icons(
                    png = moonsdk.models.get_supported_on_ramps_response_message_inner_icons_png.GetSupportedOnRampsResponse_message_inner_icons_png(
                        160x160 = '', 
                        32x32 = '', ), 
                    svg = '', ),
                icon = ''
            )
        else:
            return GetSupportedOnRampsResponseMessageInner(
                id = '',
                display_name = '',
                icons = moonsdk.models.get_supported_on_ramps_response_message_inner_icons.GetSupportedOnRampsResponse_message_inner_icons(
                    png = moonsdk.models.get_supported_on_ramps_response_message_inner_icons_png.GetSupportedOnRampsResponse_message_inner_icons_png(
                        160x160 = '', 
                        32x32 = '', ), 
                    svg = '', ),
                icon = '',
        )
        """

    def testGetSupportedOnRampsResponseMessageInner(self):
        """Test GetSupportedOnRampsResponseMessageInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
