# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from moonsdk.models.abi_input import AbiInput

class TestAbiInput(unittest.TestCase):
    """AbiInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbiInput:
        """Test AbiInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbiInput`
        """
        model = AbiInput()
        if include_optional:
            return AbiInput(
                name = '',
                type = '',
                indexed = True,
                components = [
                    moonsdk.models.abi_input.AbiInput(
                        name = '', 
                        type = '', 
                        indexed = True, 
                        components = [
                            moonsdk.models.abi_input.AbiInput(
                                name = '', 
                                type = '', 
                                indexed = True, 
                                internal_type = '', )
                            ], 
                        internal_type = '', )
                    ],
                internal_type = ''
            )
        else:
            return AbiInput(
                name = '',
                type = '',
        )
        """

    def testAbiInput(self):
        """Test AbiInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
