# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.doge_coin_api import DogeCoinApi


class TestDogeCoinApi(unittest.TestCase):
    """DogeCoinApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DogeCoinApi()

    def tearDown(self) -> None:
        pass

    def test_create_doge_coin_account(self) -> None:
        """Test case for create_doge_coin_account

        """
        pass

    def test_get_doge_coin_account(self) -> None:
        """Test case for get_doge_coin_account

        """
        pass

    def test_list_doge_coin_accounts(self) -> None:
        """Test case for list_doge_coin_accounts

        """
        pass

    def test_sign_doge_coin_transaction(self) -> None:
        """Test case for sign_doge_coin_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
