# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.supported_default_response_defaults_id import SupportedDefaultResponseDefaultsId

class TestSupportedDefaultResponseDefaultsId(unittest.TestCase):
    """SupportedDefaultResponseDefaultsId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupportedDefaultResponseDefaultsId:
        """Test SupportedDefaultResponseDefaultsId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupportedDefaultResponseDefaultsId`
        """
        model = SupportedDefaultResponseDefaultsId()
        if include_optional:
            return SupportedDefaultResponseDefaultsId(
                provider = '',
                payment_method = '',
                amount = 1.337,
                target = '',
                source = ''
            )
        else:
            return SupportedDefaultResponseDefaultsId(
                provider = '',
                payment_method = '',
                amount = 1.337,
                target = '',
                source = '',
        )
        """

    def testSupportedDefaultResponseDefaultsId(self):
        """Test SupportedDefaultResponseDefaultsId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
