# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.quote import Quote

class TestQuote(unittest.TestCase):
    """Quote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Quote:
        """Test Quote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Quote`
        """
        model = Quote()
        if include_optional:
            return Quote(
                recommendations = [
                    ''
                    ],
                payment_method = '',
                quote_id = '',
                ramp = '',
                available_payment_methods = [
                    moonsdk.models.available_payment_method.AvailablePaymentMethod(
                        icon = '', 
                        name = '', 
                        payment_type_id = '', )
                    ],
                payout = 1.337,
                transaction_fee = 1.337,
                network_fee = 1.337,
                rate = 1.337
            )
        else:
            return Quote(
                recommendations = [
                    ''
                    ],
                payment_method = '',
                quote_id = '',
                ramp = '',
                available_payment_methods = [
                    moonsdk.models.available_payment_method.AvailablePaymentMethod(
                        icon = '', 
                        name = '', 
                        payment_type_id = '', )
                    ],
                payout = 1.337,
                transaction_fee = 1.337,
                network_fee = 1.337,
                rate = 1.337,
        )
        """

    def testQuote(self):
        """Test Quote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
