# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.supported_currencies_response import SupportedCurrenciesResponse

class TestSupportedCurrenciesResponse(unittest.TestCase):
    """SupportedCurrenciesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupportedCurrenciesResponse:
        """Test SupportedCurrenciesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupportedCurrenciesResponse`
        """
        model = SupportedCurrenciesResponse()
        if include_optional:
            return SupportedCurrenciesResponse(
                message = moonsdk.models.message.Message(
                    fiat = [
                        moonsdk.models.fiat_currency.FiatCurrency(
                            icon = '', 
                            symbol = '', 
                            name = '', 
                            code = '', 
                            id = '', )
                        ], 
                    crypto = [
                        moonsdk.models.crypto_currency.CryptoCurrency(
                            network_display_name = '', 
                            icon = '', 
                            chain_id = 1.337, 
                            address = '', 
                            decimals = 1.337, 
                            network = '', 
                            symbol = '', 
                            name = '', 
                            code = '', 
                            id = '', )
                        ], )
            )
        else:
            return SupportedCurrenciesResponse(
                message = moonsdk.models.message.Message(
                    fiat = [
                        moonsdk.models.fiat_currency.FiatCurrency(
                            icon = '', 
                            symbol = '', 
                            name = '', 
                            code = '', 
                            id = '', )
                        ], 
                    crypto = [
                        moonsdk.models.crypto_currency.CryptoCurrency(
                            network_display_name = '', 
                            icon = '', 
                            chain_id = 1.337, 
                            address = '', 
                            decimals = 1.337, 
                            network = '', 
                            symbol = '', 
                            name = '', 
                            code = '', 
                            id = '', )
                        ], ),
        )
        """

    def testSupportedCurrenciesResponse(self):
        """Test SupportedCurrenciesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
