# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ens_reverse_resolve_response import ENSReverseResolveResponse

class TestENSReverseResolveResponse(unittest.TestCase):
    """ENSReverseResolveResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ENSReverseResolveResponse:
        """Test ENSReverseResolveResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ENSReverseResolveResponse`
        """
        model = ENSReverseResolveResponse()
        if include_optional:
            return ENSReverseResolveResponse(
                domain = ''
            )
        else:
            return ENSReverseResolveResponse(
                domain = '',
        )
        """

    def testENSReverseResolveResponse(self):
        """Test ENSReverseResolveResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
