# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.get_supported_on_ramps_response_message_inner_icons import GetSupportedOnRampsResponseMessageInnerIcons

class TestGetSupportedOnRampsResponseMessageInnerIcons(unittest.TestCase):
    """GetSupportedOnRampsResponseMessageInnerIcons unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSupportedOnRampsResponseMessageInnerIcons:
        """Test GetSupportedOnRampsResponseMessageInnerIcons
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSupportedOnRampsResponseMessageInnerIcons`
        """
        model = GetSupportedOnRampsResponseMessageInnerIcons()
        if include_optional:
            return GetSupportedOnRampsResponseMessageInnerIcons(
                png = moonsdk.models.get_supported_on_ramps_response_message_inner_icons_png.GetSupportedOnRampsResponse_message_inner_icons_png(
                    160x160 = '', 
                    32x32 = '', ),
                svg = ''
            )
        else:
            return GetSupportedOnRampsResponseMessageInnerIcons(
                png = moonsdk.models.get_supported_on_ramps_response_message_inner_icons_png.GetSupportedOnRampsResponse_message_inner_icons_png(
                    160x160 = '', 
                    32x32 = '', ),
                svg = '',
        )
        """

    def testGetSupportedOnRampsResponseMessageInnerIcons(self):
        """Test GetSupportedOnRampsResponseMessageInnerIcons"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
