# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.ens_api import ENSApi


class TestENSApi(unittest.TestCase):
    """ENSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ENSApi()

    def tearDown(self) -> None:
        pass

    def test_resolve(self) -> None:
        """Test case for resolve

        """
        pass


if __name__ == '__main__':
    unittest.main()
