# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.transaction_data import TransactionData

class TestTransactionData(unittest.TestCase):
    """TransactionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionData:
        """Test TransactionData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionData`
        """
        model = TransactionData()
        if include_optional:
            return TransactionData(
                moon_scan_url = '',
                transaction_hash = '',
                signed_transaction = '',
                signed_message = '',
                raw_transaction = '',
                signature = '',
                transaction = openapi_client.models.tx.Tx(
                    type = 1.337, 
                    chain_id = 1.337, 
                    data = '', 
                    gas = '', 
                    gas_price = '', 
                    gas_tip_cap = '', 
                    gas_fee_cap = '', 
                    value = '', 
                    nonce = 1.337, 
                    from = '', 
                    to = '', 
                    blob_gas = '', 
                    blob_gas_fee_cap = '', 
                    blob_hashes = [
                        ''
                        ], 
                    v = '', 
                    r = '', 
                    s = '', ),
                user_ops = [
                    openapi_client.models.transaction_request.TransactionRequest(
                        nonce = '', 
                        data = '', 
                        value = '', 
                        to = '', 
                        from = '', 
                        max_fee_per_gas = '', 
                        max_priority_fee_per_gas = '', )
                    ],
                userop_transaction = ''
            )
        else:
            return TransactionData(
                transaction_hash = '',
                signed_transaction = '',
        )
        """

    def testTransactionData(self):
        """Test TransactionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
