# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.inft_approval_erc1155 import INFTApprovalERC1155

class TestINFTApprovalERC1155(unittest.TestCase):
    """INFTApprovalERC1155 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> INFTApprovalERC1155:
        """Test INFTApprovalERC1155
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `INFTApprovalERC1155`
        """
        model = INFTApprovalERC1155()
        if include_optional:
            return INFTApprovalERC1155(
                transaction_hash = '',
                contract = '',
                log_index = '',
                account = '',
                operator = '',
                approved = True,
                token_contract_type = '',
                token_name = '',
                token_symbol = ''
            )
        else:
            return INFTApprovalERC1155(
                transaction_hash = '',
                contract = '',
                log_index = '',
                account = '',
                operator = '',
                approved = True,
                token_contract_type = '',
                token_name = '',
                token_symbol = '',
        )
        """

    def testINFTApprovalERC1155(self):
        """Test INFTApprovalERC1155"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
