# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.erc20_api import Erc20Api


class TestErc20Api(unittest.TestCase):
    """Erc20Api unit test stubs"""

    def setUp(self) -> None:
        self.api = Erc20Api()

    def tearDown(self) -> None:
        pass

    def test_allowance_erc20(self) -> None:
        """Test case for allowance_erc20

        """
        pass

    def test_approve_erc20(self) -> None:
        """Test case for approve_erc20

        """
        pass

    def test_balance_of_erc20(self) -> None:
        """Test case for balance_of_erc20

        """
        pass

    def test_decimals_erc20(self) -> None:
        """Test case for decimals_erc20

        """
        pass

    def test_name_erc20(self) -> None:
        """Test case for name_erc20

        """
        pass

    def test_symbol_erc20(self) -> None:
        """Test case for symbol_erc20

        """
        pass

    def test_total_supply_erc20(self) -> None:
        """Test case for total_supply_erc20

        """
        pass

    def test_transfer_erc20(self) -> None:
        """Test case for transfer_erc20

        """
        pass

    def test_transfer_from_erc20(self) -> None:
        """Test case for transfer_from_erc20

        """
        pass


if __name__ == '__main__':
    unittest.main()
