# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.solana_api import SolanaApi


class TestSolanaApi(unittest.TestCase):
    """SolanaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SolanaApi()

    def tearDown(self) -> None:
        pass

    def test_create_solana_account(self) -> None:
        """Test case for create_solana_account

        """
        pass

    def test_get_solana_account(self) -> None:
        """Test case for get_solana_account

        """
        pass

    def test_list_solana_accounts(self) -> None:
        """Test case for list_solana_accounts

        """
        pass

    def test_sign_solana_transaction(self) -> None:
        """Test case for sign_solana_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
