# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.crypto_currency import CryptoCurrency

class TestCryptoCurrency(unittest.TestCase):
    """CryptoCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CryptoCurrency:
        """Test CryptoCurrency
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CryptoCurrency`
        """
        model = CryptoCurrency()
        if include_optional:
            return CryptoCurrency(
                network_display_name = '',
                icon = '',
                chain_id = 1.337,
                address = '',
                decimals = 1.337,
                network = '',
                symbol = '',
                name = '',
                code = '',
                id = ''
            )
        else:
            return CryptoCurrency(
                network_display_name = '',
                icon = '',
                chain_id = 1.337,
                address = '',
                decimals = 1.337,
                network = '',
                symbol = '',
                name = '',
                code = '',
                id = '',
        )
        """

    def testCryptoCurrency(self):
        """Test CryptoCurrency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
