# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.erc4337_api import Erc4337Api


class TestErc4337Api(unittest.TestCase):
    """Erc4337Api unit test stubs"""

    def setUp(self) -> None:
        self.api = Erc4337Api()

    def tearDown(self) -> None:
        pass

    def test_get_address(self) -> None:
        """Test case for get_address

        """
        pass

    def test_sign_broadcast_user_op_tx(self) -> None:
        """Test case for sign_broadcast_user_op_tx

        """
        pass


if __name__ == '__main__':
    unittest.main()
