# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.api.litecoin_api import LitecoinApi


class TestLitecoinApi(unittest.TestCase):
    """LitecoinApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LitecoinApi()

    def tearDown(self) -> None:
        pass

    def test_create_litecoin_account(self) -> None:
        """Test case for create_litecoin_account

        """
        pass

    def test_get_litecoin_account(self) -> None:
        """Test case for get_litecoin_account

        """
        pass

    def test_list_litecoin_accounts(self) -> None:
        """Test case for list_litecoin_accounts

        """
        pass

    def test_sign_litecoin_transaction(self) -> None:
        """Test case for sign_litecoin_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
