# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moonsdk.models.bitcoin_cash_transaction_input import BitcoinCashTransactionInput

class TestBitcoinCashTransactionInput(unittest.TestCase):
    """BitcoinCashTransactionInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BitcoinCashTransactionInput:
        """Test BitcoinCashTransactionInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BitcoinCashTransactionInput`
        """
        model = BitcoinCashTransactionInput()
        if include_optional:
            return BitcoinCashTransactionInput(
                to = '',
                value = 1.337,
                network = '',
                compress = True
            )
        else:
            return BitcoinCashTransactionInput(
        )
        """

    def testBitcoinCashTransactionInput(self):
        """Test BitcoinCashTransactionInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
