# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.erc1155_api import ERC1155Api


class TestERC1155Api(unittest.TestCase):
    """ERC1155Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ERC1155Api()

    def tearDown(self) -> None:
        pass

    def test_balance_of(self) -> None:
        """Test case for balance_of

        """
        pass

    def test_balance_of_batch(self) -> None:
        """Test case for balance_of_batch

        """
        pass

    def test_is_approved_for_all(self) -> None:
        """Test case for is_approved_for_all

        """
        pass

    def test_safe_batch_transfer_from(self) -> None:
        """Test case for safe_batch_transfer_from

        """
        pass

    def test_safe_transfer_from(self) -> None:
        """Test case for safe_transfer_from

        """
        pass

    def test_set_approval_for_all(self) -> None:
        """Test case for set_approval_for_all

        """
        pass


if __name__ == '__main__':
    unittest.main()
