# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.conveyor_finance_controller_response import ConveyorFinanceControllerResponse

class TestConveyorFinanceControllerResponse(unittest.TestCase):
    """ConveyorFinanceControllerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConveyorFinanceControllerResponse:
        """Test ConveyorFinanceControllerResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConveyorFinanceControllerResponse`
        """
        model = ConveyorFinanceControllerResponse()
        if include_optional:
            return ConveyorFinanceControllerResponse(
                input = openapi_client.models.input_body.InputBody(
                    to = '', 
                    data = '', 
                    input = '', 
                    value = '', 
                    nonce = '', 
                    gas = '', 
                    gas_price = '', 
                    chain_id = '', 
                    encoding = '', 
                    eoa = True, 
                    contract_address = '', 
                    token_id = '', 
                    token_ids = '', 
                    approved = True, 
                    broadcast = True, ),
                convey = openapi_client.models.transaction_response.TransactionResponse(
                    message = '', 
                    tx = openapi_client.models.transaction_response_tx.TransactionResponse_tx(
                        data = '', 
                        value = '', 
                        nonce = 1.337, 
                        gas = '', 
                        to = '', 
                        from = '', ), 
                    info = openapi_client.models.transaction_response_info.TransactionResponse_info(
                        conveyor_gas = '', 
                        affiliate_gas = '', 
                        affiliate_aggregator = '', 
                        amount_out = '', 
                        amount_out_min = '', ), 
                    chain_id = 1.337, 
                    current_block_number = 1.337, ),
                data = openapi_client.models.transaction.Transaction(
                    moon_scan_url = '', 
                    transaction_hash = '', 
                    signed_transaction = '', 
                    signed_message = '', 
                    raw_transaction = '', 
                    signature = '', 
                    transaction = {
                        'key' : openapi_client.models.tx.Tx(
                            type = 1.337, 
                            chain_id = 1.337, 
                            data = '', 
                            gas = '', 
                            gas_price = '', 
                            gas_tip_cap = '', 
                            gas_fee_cap = '', 
                            value = '', 
                            nonce = 1.337, 
                            from = '', 
                            to = '', 
                            blob_gas = '', 
                            blob_gas_fee_cap = '', 
                            blob_hashes = [
                                ''
                                ], 
                            v = '', 
                            r = '', 
                            s = '', )
                        }, 
                    user_ops = [
                        openapi_client.models.transaction_request.TransactionRequest(
                            nonce = '', 
                            data = '', 
                            value = '', 
                            to = '', 
                            from = '', 
                            max_fee_per_gas = '', 
                            max_priority_fee_per_gas = '', )
                        ], 
                    userop_transaction = '', ),
                tx = openapi_client.models.transaction_response_tx.TransactionResponse_tx(
                    data = '', 
                    value = '', 
                    nonce = 1.337, 
                    gas = '', 
                    to = '', 
                    from = '', ),
                signed = openapi_client.models.transaction.Transaction(
                    moon_scan_url = '', 
                    transaction_hash = '', 
                    signed_transaction = '', 
                    signed_message = '', 
                    raw_transaction = '', 
                    signature = '', 
                    transaction = {
                        'key' : openapi_client.models.tx.Tx(
                            type = 1.337, 
                            chain_id = 1.337, 
                            data = '', 
                            gas = '', 
                            gas_price = '', 
                            gas_tip_cap = '', 
                            gas_fee_cap = '', 
                            value = '', 
                            nonce = 1.337, 
                            from = '', 
                            to = '', 
                            blob_gas = '', 
                            blob_gas_fee_cap = '', 
                            blob_hashes = [
                                ''
                                ], 
                            v = '', 
                            r = '', 
                            s = '', )
                        }, 
                    user_ops = [
                        openapi_client.models.transaction_request.TransactionRequest(
                            nonce = '', 
                            data = '', 
                            value = '', 
                            to = '', 
                            from = '', 
                            max_fee_per_gas = '', 
                            max_priority_fee_per_gas = '', )
                        ], 
                    userop_transaction = '', ),
                success = True,
                message = ''
            )
        else:
            return ConveyorFinanceControllerResponse(
                success = True,
                message = '',
        )
        """

    def testConveyorFinanceControllerResponse(self):
        """Test ConveyorFinanceControllerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
